//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note()
        {
            this.DownloadedNotes = new HashSet<DownloadedNote>();
            this.NoteReviews = new HashSet<NoteReview>();
            this.RejectedNotes = new HashSet<RejectedNote>();
        }
    
        public int NoteID { get; set; }

        public int SellerID { get; set; }

        public Nullable<int> ActionedBy { get; set; }

        [Required(ErrorMessage ="Please Enter Note Title")]
        public string NoteTitle { get; set; }

        [Required(ErrorMessage ="Please Select Note Category")]
        public int Category { get; set; }

        public string DisplayPicture { get; set; }

        public string AdminRemarks { get; set; }

        [Required(ErrorMessage ="Please Enter your Note")]
        public string NoteAttachment { get; set; }

        public Nullable<decimal> NoteSize { get; set; }

        [Required(ErrorMessage ="Please Select Note Type")]
        public int NoteType { get; set; }


        public Nullable<int> Pages { get; set; }

        [Required(ErrorMessage ="Please Enter Note Description")]
        public string NoteDescription { get; set; }

        
        public int Country { get; set; }


        public string Institute { get; set; }
        public string CourseName { get; set; }
        public string CourseCode { get; set; }
        public string Professor { get; set; }

        [Required(ErrorMessage ="Please Choose Selling Mode")]
        public int SellFor { get; set; }
        public string NotePreview { get; set; }

        [Required(ErrorMessage ="Please Enter Price of Note")]
        public Nullable<decimal> SellPrice { get; set; }
        public int Status { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DownloadedNote> DownloadedNotes { get; set; }
        public virtual User User { get; set; }
        public virtual NoteCategory NoteCategory { get; set; }
        public virtual NoteCountry NoteCountry { get; set; }
        public virtual NoteType NoteType1 { get; set; }
        public virtual Note Note1 { get; set; }
        public virtual Note Note2 { get; set; }
        public virtual ReferenceData ReferenceData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteReview> NoteReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RejectedNote> RejectedNotes { get; set; }

        //public SelectList CategoryList { get; set; }

        public HttpPostedFileBase BookImage { get; set; }

        public HttpPostedFileBase NotePdf { get; set; }

        public HttpPostedFileBase PreviewOfNote { get; set; }

        public List<Note> DisplayNote { get; set; }

        


    }
}
