//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;
    
    public partial class Profile
    {
        public int ID { get; set; }
        public Nullable<int> SellerID { get; set; }
        public string SecondaryEmailID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Gender { get; set; }

        [Required(ErrorMessage = "Please Enter Phone No")]
        public string PhoneNo { get; set; }
        public int CountryCode { get; set; }
        public string ProfilePhoto { get; set; }

        [Required(ErrorMessage ="Please Enter Address1")]
        public string Address1 { get; set; }


       [Required(ErrorMessage ="Please Enter Adddress2")]
        public string Address2 { get; set; }


       [Required(ErrorMessage ="Please Enter City Name")]
        public string City { get; set; }


        [Required(ErrorMessage ="Please Enter State ")]
        public string State { get; set; }


        [Required(ErrorMessage ="Please Enter ZipCode")]
        public string ZipCode { get; set; }


        [Required(ErrorMessage ="Please Enter Country")]
        public string Country { get; set; }


        public string University { get; set; }
        public string College { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ReferenceData ReferenceData { get; set; }
        public virtual User User { get; set; }

        public HttpPostedFileBase UserImage { get; set; }
    }
}
