//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.DownloadedNotes = new HashSet<DownloadedNote>();
            this.DownloadedNotes1 = new HashSet<DownloadedNote>();
            this.Notes = new HashSet<Note>();
            this.NoteReviews = new HashSet<NoteReview>();
            this.Profiles = new HashSet<Profile>();
            this.RejectedNotes = new HashSet<RejectedNote>();
        }
    
        public int ID { get; set; }
        public int RoleID { get; set; }

        [Required(ErrorMessage = "Please Enter Email Id")]
        [EmailAddress(ErrorMessage ="Plase Enter a Valid Email Id")]
        public string EmailID { get; set; }

        [Required(ErrorMessage = "Please Enter First Name")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])[A-Za-z]{1,}", ErrorMessage = "Enater Valid Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage ="Please Enter Last Name")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])[A-Za-z]{1,}", ErrorMessage = "Enater Valid Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage ="Plase Enter Password")]
       /* [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{6,24}", ErrorMessage =  "Password must be between 6 and 24 characters long."+
           "It must have at least 1 lowercase character."+
            "It must have at least 1 special character."+
            "It must have at least 1 digit character."+
            "It must not contain white spaces")]*/
        public string Password { get; set; }

        public bool IsEmailVerified { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }

        public Nullable<int> CreatedBy { get; set; }

        public Nullable<System.DateTime> ModifiedDate { get; set; }

        public Nullable<int> ModifiedBy { get; set; }

        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DownloadedNote> DownloadedNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DownloadedNote> DownloadedNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteReview> NoteReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile> Profiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RejectedNote> RejectedNotes { get; set; }
        public virtual UserRole UserRole { get; set; }

        public string LoginErrorMessage { get; set; }

        public bool RememberMe { get; set; }

        [Required(ErrorMessage ="Please enter your conform password")]
        [Compare(@"Password", ErrorMessage ="Password dose not match")]
        public string conform_password { get; set; }
    }
}
